spring:
  application:
    name: eureka_server
server:
  port: 8090


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false   # disables the warning in development
    eviction-interval-timer-in-ms: 5000
